# Generated by Django 4.2.2 on 2023-06-26 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del producto')),
                ('title', models.CharField(max_length=120, verbose_name='Título del producto')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Descripción textual del producto')),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=15, verbose_name='Precio del producto en USD')),
            ],
        ),
    ]
